### ISSUE TITLE
upsert does not remove duplicates from group list 

### ISSUE THREAD

**Issue by 45cali** [keikoproj/aws-auth#50]
running this command multiple times does not remove duplicates from group list
```
upsert  --maproles --rolearn <rolearn>   --append --groups testing --username foo --update-username=false
role <rolearn> has been updated
```

result
```
apiVersion: v1
data:
  mapRoles: |
    - rolearn: <rolearn>
      username: foo
      groups:
      - testing
      - testing
      - testing
```
